<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.embabel.common</groupId>
        <artifactId>embabel-common-parent</artifactId>
        <version>0.1.1-7Z</version>
    </parent>
    <artifactId>embabel-common-test</artifactId>
    <packaging>pom</packaging>
    <name>Embabel Common Test Parent</name>
    <description>Embabel Test Classes and Framework shared across Embabel Modules.</description>

    <properties>
        <mockk.version>1.13.3</mockk.version>
    </properties>

    <modules>
        <module>embabel-common-test-dependencies</module>
        <module>embabel-common-test-ai</module>
        <module>embabel-common-test-neo</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.embabel.common</groupId>
            <artifactId>embabel-common-util</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>

        <dependency>
            <groupId>io.mockk</groupId>
            <artifactId>mockk-jvm</artifactId>
            <version>${mockk.version}</version>
        </dependency>

    </dependencies>


</project>
