<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.embabel.common</groupId>
        <artifactId>embabel-common-test</artifactId>
        <version>0.1.1-7Z</version>
    </parent>
    <artifactId>embabel-common-test-ai</artifactId>
    <packaging>jar</packaging>
    <name>Embabel Common Test AI</name>
    <description>Embabel AI Framework for Unit and Integration Tests</description>

    <dependencies>
        <dependency>
            <groupId>com.embabel.common</groupId>
            <artifactId>embabel-common-util</artifactId>
        </dependency>

        <dependency>
            <groupId>com.embabel.common</groupId>
            <artifactId>embabel-common-ai</artifactId>
        </dependency>
    </dependencies>

</project>
