<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.embabel.build</groupId>
        <artifactId>embabel-dependencies-parent</artifactId>
        <version>0.1.3-7Z</version>
        <relativePath />
    </parent>
    <groupId>com.embabel.common</groupId>
    <artifactId>embabel-common-test-dependencies</artifactId>
    <version>0.1.3-7Z</version>
    <packaging>pom</packaging>
    <name>Embabel Common Test Dependencies</name>
    <description>Embabel Common Test Framework Dependencies</description>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.embabel.common</groupId>
                <artifactId>embabel-common-test-ai</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.embabel.common</groupId>
                <artifactId>embabel-common-test-neo</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <repositories>
         <repository>
            <id>embabel-releases</id>
            <url>https://repo.embabel.com/artifactory/libs-releases</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>embabel-snapshots</id>
            <url>https://repo.embabel.com/artifactory/libs-snapshot</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>
